#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# bootstrap/setup_shell.sh – Idempotent shell profile setup
# ---------------------------------------------------------------------------
# Creates minimal bash profile that sources from the dotfiles repo.
# BASH ONLY - users must switch to bash for full functionality.
# ---------------------------------------------------------------------------
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASH_PROFILE="$HOME/.bash_profile"
ZSH_RC="$HOME/.zshrc"

echo "==> Setting up shell profile..."

# Create bash profile
cat > "$BASH_PROFILE" <<'EOF'
# Bash profile - sources all configuration from dotfiles
# Auto-generated by dotfiles/bootstrap/setup_shell.sh

# Silence the annoying macOS "zsh is now default" warning
export BASH_SILENCE_DEPRECATION_WARNING=1

export DOTFILES_DIR="${DOTFILES_DIR:-$HOME/dotfiles}"

# Source the main bashrc from dotfiles
if [ -r "$DOTFILES_DIR/shell/bashrc" ]; then
  . "$DOTFILES_DIR/shell/bashrc"
fi
EOF
echo "✔ Created $BASH_PROFILE"

# Create .zshrc that tells user to switch to bash
cat > "$ZSH_RC" <<'EOF'
# ============================================================================
# These dotfiles require bash.
# Please switch your default shell to bash:
#
#   chsh -s /bin/bash
#
# Then close this terminal and open a new one.
# ============================================================================

echo ""
echo "⚠️  These dotfiles are configured for bash only."
echo "    Please switch to bash: chsh -s /bin/bash"
echo "    Then restart your terminal."
echo ""
EOF
echo "✔ Created $ZSH_RC (bash-only notice)"

echo ""
echo "✔ Shell setup complete"
echo ""
echo "⚠️  IMPORTANT: Switch to bash as your default shell:"
echo "    chsh -s /bin/bash"
echo ""
echo "Then close all terminals and open a new one."
