#!/usr/bin/env bash
# -------------------------------------------------------------
# 20_aliases_common – aliases that work in BOTH bash and zsh
# -------------------------------------------------------------

# Reload rc file quickly ------------------------------------------------------
alias src='source ~/.bashrc'

# Safety ----------------------------------------------------------------------
alias mv='mv -i'
alias rm='rm -I -v'
alias cp='cp -i'
alias chmod='chmod --preserve-root'
alias chown='chown --preserve-root'

# Navigation ------------------------------------------------------------------
alias u='cd ..'
alias uu='cd ../..'
alias uuu='cd ../../..'
alias uuuu='cd ../../../..'
alias uuuuu='cd ../../../../..'

# System stuff ----------------------------------------------------------------
alias fd='fdfind'
alias ctl='systemctl'
alias tidy='make clang-tidy'
alias fast='make -j$(nproc 2>/dev/null || sysctl -n hw.ncpu)'
alias fastclean='make clean && fast'
alias ja='ninja -j$(nproc 2>/dev/null || sysctl -n hw.ncpu)'
alias rml='rm *.log'
alias ws='wireshark'

# Zeek ------------------------------------------------------------------------
alias zeek_run='zeek_runner'
alias zr='zeek_run'
alias zrf='zr -f'
alias zrb='zr --build'
alias zrp='zr --pcap'
alias zrl='zr -l'
alias zc='zeek-config'

# eza (modern ls replacement) --------------------------------------------------
alias eza="eza --binary --color auto --group-directories-first --git --git-repos-no-status --hyperlink --icons auto --mounts --no-permissions --octal-permissions --time-style long-iso"
alias ls='eza'
alias e="eza --all --long"
alias ea="eza --all"
alias el="eza --long"
alias eld="eza --all --long --only-dirs --sort name"
alias esize="eza --long --sort size"
alias et="eza --long --sort modified"
alias etree="eza --tree"
alias la='ea'
alias lsa='ea'
alias l='e'
alias ll='el'
alias lt='et'
alias lsize='esize'
alias lld='eld'
alias lsl='ls -l'
alias lsla='ls -la'
alias cat='bat'

# grep / search ---------------------------------------------------------------
alias grep='rg'   # use ripgrep everywhere
alias ag='rg'

# nix
alias ns='nix-switch'
alias nu='nix-update'

# Git -------------------------------------------------------------------------
alias clone='git clone'
alias pull='git pull'
alias gs='git status'
alias gd='git diff'
alias gb='git branch'
alias gaa='git add -A'
alias gad='git add -u'
alias gcm='git commit -m'

# Code editor -----------------------------------------------------------------
alias c='code'
alias scode='sudo code --no-sandbox --user-data-dir="~/.vscode-root"'

alias z='zed'

# Project helpers / UV --------------------------------------------------------
alias python='uv run -- python3'
alias python3='uv run -- python3'
alias pip='uv pip'
alias pipx='uv tool'
alias uvp='uv pip'
alias uvs='uv sync'
alias uvclean='rm -rf .venv && uv venv'

# Work shortcuts --------------------------------------------------------------
export WORK_ROOT="${WORK_ROOT:-$HOME/work}"

export PARSERS_ROOT="${PARSERS_ROOT:-$WORK_ROOT/parsers}"
export ICSNPP_ROOT="${ICSNPP_ROOT:-$PARSERS_ROOT/icsnpp}"
export JJRUSH_ROOT="${JJRUSH_ROOT:-$PARSERS_ROOT/jjrush}"
export PARSITECTS_ROOT="${PARSITECTS_ROOT:-$PARSERS_ROOT/parsitects}"

export MACLOLM_ROOT="${MACLOLM_ROOT:-$WORK_ROOT/malcolm}"

alias work='cd $WORK_ROOT'
alias parsers='cd $PARSERS_ROOT'
alias malcolm='cd $MACLOLM_ROOT'

alias malc='malcolm'
alias mal='malc'

alias ics='cd $ICSNPP_ROOT'
alias parse='parsers'
alias par='parsers'

# Other repo shortcuts
alias spud='cd ~/research/spuddy/'
alias spuddy='spud'

# Local Repositories ---------------------------------------------------------------
alias opc='cd $PARSERS_ROOT/icsnpp-opcua-binary'
alias roc='cd $PARSERS_ROOT/icsnpp-roc-plus'
alias omr='cd $PARSERS_ROOT/icsnpp-omron-fins'
alias c12='cd $PARSERS_ROOT/C12.22'

alias dot='cd $DOTFILES_DIR' # overides /usr/bin/dot
alias dotdot='dot'
alias dd='dotdot' # overides /usr/bin/dd

# Editing helpers -------------------------------------------------------------
alias cenv='c "$DOTFILES_DIR/shell/common/00_env"'
alias clias='c "$DOTFILES_DIR/shell/common/20_aliases_common"'
alias cdock='c "$DOTFILES_DIR/shell/common/30_docker_aliases"'
alias cfunc='c $DOTFILES_DIR/shell/common/40_functions'
alias cbash='c "$DOTFILES_DIR/shell/bash/00_interactive"'
alias czsh='c "$DOTFILES_DIR/shell/zsh/00_interactive"'

# Tool updaters + launchers ---------------------------------------------------
alias codex='codex_update_and_run'
alias claude='claude_update_and_run'
alias gemini='gemini_update_and_run'
